frontend/src/assets/base.css
frontend/src/router/index.ts

base.cssとindex.tsをなおした

---

backend/handler/api.gen.go
backend/handler/camps.go
backend/handler/events.go
backend/handler/questions.go
backend/handler/staffs.go
backend/handler/users.go
openapi.yaml

mdに書いてあるAPI仕様をOpenAPIに書き起こす

---

backend/handler/api.gen.go
backend/handler/events.go
backend/handler/questions.go
backend/model/model.go
backend/model/question.go
backend/repository/question.go
openapi.yaml

質問を作成・編集・削除できるように

---

backend/handler/api.gen.go
backend/handler/events.go
backend/model/event.go
openapi.yaml

合宿係としてイベントを追加できるように

---

backend/handler/api.gen.go
backend/handler/questions.go
backend/model/model.go
backend/model/question.go
backend/repository/question.go
openapi.yaml

#41 に関連して、選択肢そのものに対する検索をかけたりしたいことはなさそうなので単純な配列で管理するようにした

選択肢を単純な配列で管理する

---

backend/main.go

localhost:5173がCORSに引っかからないようにする

---

backend/model/event.go
backend/model/question.go

nullableな値にのみポインタを使うよう修正

---

backend/handler/api.gen.go
backend/handler/camps.go
backend/model/camp.go
backend/model/event.go
backend/model/model.go
backend/repository/camp.go
frontend/src/api/schema.d.ts
openapi.yaml

合宿のしおりの追加等をできるように

---

backend/handler/api.gen.go
backend/handler/budgets.go
backend/model/budget.go
backend/model/model.go
backend/repository/budget.go
frontend/src/api/schema.d.ts
openapi.yaml

予算を取得できるようにする

---

backend/handler/answers.go
backend/handler/api.gen.go
backend/handler/questions.go
backend/model/answer.go
backend/model/question.go
backend/model/user.go
backend/repository/answer.go
frontend/src/api/schema.d.ts
openapi.yaml

自分の回答を取得できるようにする

---

backend/handler/questions.go

POST /api/questionsのレスポンスが配列になっていたのを修正

---

backend/handler/api.gen.go
backend/handler/camps.go
backend/model/camp.go
backend/repository/camp.go
frontend/src/api/schema.d.ts
openapi.yaml

デフォルトの合宿の情報を取得する

---

backend/handler/answers.go
backend/handler/api.gen.go
backend/repository/answer.go
frontend/src/api/schema.d.ts
openapi.yaml

回答を編集できるようにする

---

backend/handler/answers.go
backend/handler/api.gen.go
backend/handler/budgets.go
backend/handler/camps.go
backend/handler/events.go
backend/handler/options.go
backend/handler/question_groups.go
backend/handler/questions.go
backend/handler/staffs.go
backend/handler/users.go
frontend/src/api/schema.d.ts
openapi.yaml

`X-Forwarded-User`をAPI定義上はoptionalにする

---

backend/handler/answers.go
backend/handler/api.gen.go
backend/model/answer.go
frontend/src/api/schema.d.ts
openapi.yaml

回答の複数選択を実装

---

backend/handler/api.gen.go
backend/model/camp.go
backend/model/question_group.go
frontend/src/api/schema.d.ts
openapi.yaml

質問グループと合宿を紐づける

---

backend/handler/camps.go
backend/handler/events.go
backend/handler/questions.go
backend/handler/staffs.go
backend/handler/users.go
backend/model/model.go

Not Foundエラーを返す

---

frontend/env.d.ts
frontend/src/api/handler.ts
frontend/src/views/GuidebookView.vue

合宿のしおりのapi接続

---

backend/handler/api.gen.go
backend/handler/budgets.go
backend/repository/budget.go
frontend/src/api/schema.d.ts
openapi.yaml

合宿係が予算を設定・変更できるようにする

---

backend/handler/api.gen.go
backend/model/budget.go
frontend/src/api/schema.d.ts
openapi.yaml

予算に支払済みの金額の情報を含める

---

backend/handler/answers.go
backend/handler/api.gen.go
frontend/src/api/schema.d.ts
openapi.yaml

合宿係が他人の回答を編集できるように

---

backend/repository/budget.go

予算取得・作成時にデフォルトの合宿のIDを指定

---

frontend/src/components/information/PaymentInformationPanel.vue
frontend/src/router/index.ts
frontend/src/views/UserInformationView.vue
frontend/src/views/admin/AdminPayments.vue

支払い確認作業のページ

---

backend/go.mod
backend/go.sum
backend/main.go
backend/migration/migrate.go
backend/migration/v1.go

支払い情報のマイグレーション

---

backend/migration/migrate.go
backend/migration/v2.go

外部キー制約なども考慮してマイグレーションする

---

backend/migration/v2.go

`Answers`は今回関係ないので削除

---

backend/migration/v2.go

外部キーを正しく設定

---

backend/migration/migrate.go
backend/migration/v2.go

テーブル作成のため`AutoMigrate`を使用

---

frontend/src/views/admin/AdminPayments.vue

operatorIdの初期化ミスを修正

---

frontend/src/views/admin/AdminPayments.vue

バグの原因がわからないので、いったんハードコードします
マジでごめんなさい

operatorIdを一時的に変更

---

backend/handler/api.gen.go
backend/handler/question_groups.go
backend/repository/question_group.go
frontend/src/api/schema.d.ts
openapi.yaml

質問グループのidからの取得用api

---

backend/handler/api.gen.go
backend/handler/question_groups.go
backend/repository/question_group.go
frontend/src/api/schema.d.ts
openapi.yaml

削除用のapiを作成しました。
対応するidがない場合も204を返してます。(子質問がそうだった)

質問グループの削除api
